settings:
  # Не менять, чтобы не сбросился конфиг, когда не нужно.
  config-version: 1.0

  # Форматирование текста.
  # LEGACY - цвет через & и hex &# (Работает только на: 1.16+)
  # LEGACY_ADVANCED - улучшенный аналог legacy с поддержкой &## формата hex (&##123 = &#112233) (Работает только на: 1.16+)
  # MINIMESSAGE - цвет через <цвет></цвет> (Работает только на: 1.17+)
  # VANILLA - дефолтное форматирование через &
  colorizer-mode: LEGACY_ADVANCED

  # Настройка основной команды и её альясов.
  command: "exp"
  aliases: []

  # Требовать ли бутылку для обмена опыта?
  require-bottle: false

messages:
  reload: "&aПлагин успешно перезагружен!"
  no-permission: "&cИзвините, но у вас нет прав, чтобы конвертировать опыта!"
  player-not-found: "&cИгрок &4{player}&c не был найден!"
  usage-error: "&cОшибка! &fИспользуй: /exp <количество>"
  usage-error-if-has-extended-perms: "&cОшибка! &fИспользуй: /exp <количество> &7(<игрок>) (force)"
  amount-error: "&cОшибка, Вы указали неверное число!"
  no-bottle: "&cДля этого нужен хотя бы 1 пустой бутылёк!"
  no-bottle-if-other: "&cУ игрока &4{player}&c нету пустого бутылька!"
  not-enough: "&cНедостаточно опыта!"
  not-enough-if-other: "&cУ игрока &4{player}&c Недостаточно опыта!"
